[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true

[colors.primary]
background = "#222222"

[cursor]
style = { blinking = "Always" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

[font]

size = 11

[font.normal]

family = "JetBrainsMono Nerd Font"
